// <auto-generated />
using System;
using EasyPDV.BackEnd.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyPDV.BackEnd.Infra.Migrations
{
    [DbContext(typeof(PdvDbContext))]
    partial class PdvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.Cashier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CashierNumber")
                        .HasColumnType("int");

                    b.Property<string>("CashierResponsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cashier", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid?>("RegularSaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegularSaleId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.CashierBleed", b =>
                {
                    b.HasBaseType("EasyPDV.BackEnd.Domain.Entities.Cashier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.ToTable("CashierBleed");
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.CashierOpen", b =>
                {
                    b.HasBaseType("EasyPDV.BackEnd.Domain.Entities.Cashier");

                    b.Property<double>("InitialBalance")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.ToTable("CashierOpen", (string)null);
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.CancelledSale", b =>
                {
                    b.HasBaseType("EasyPDV.BackEnd.Domain.Entities.Sale");

                    b.ToTable("CancelledSales", (string)null);
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.IndividualSale", b =>
                {
                    b.HasBaseType("EasyPDV.BackEnd.Domain.Entities.Sale");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProductId");

                    b.ToTable("IndividualSales", (string)null);
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.RegularSale", b =>
                {
                    b.HasBaseType("EasyPDV.BackEnd.Domain.Entities.Sale");

                    b.ToTable("RegularSales", (string)null);
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.ReversedSale", b =>
                {
                    b.HasBaseType("EasyPDV.BackEnd.Domain.Entities.Sale");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductChangeFromId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductChangeToId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProductChangeFromId");

                    b.HasIndex("ProductChangeToId");

                    b.ToTable("ReversedSales", (string)null);
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.Product", b =>
                {
                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.RegularSale", null)
                        .WithMany("Products")
                        .HasForeignKey("RegularSaleId");
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.CashierOpen", b =>
                {
                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Cashier", null)
                        .WithOne()
                        .HasForeignKey("EasyPDV.BackEnd.Domain.Entities.CashierOpen", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.CancelledSale", b =>
                {
                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Sale", null)
                        .WithOne()
                        .HasForeignKey("EasyPDV.BackEnd.Domain.Entities.CancelledSale", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.IndividualSale", b =>
                {
                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Sale", null)
                        .WithOne()
                        .HasForeignKey("EasyPDV.BackEnd.Domain.Entities.IndividualSale", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.RegularSale", b =>
                {
                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Sale", null)
                        .WithOne()
                        .HasForeignKey("EasyPDV.BackEnd.Domain.Entities.RegularSale", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.ReversedSale", b =>
                {
                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Sale", null)
                        .WithOne()
                        .HasForeignKey("EasyPDV.BackEnd.Domain.Entities.ReversedSale", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Product", "ProductChangeFrom")
                        .WithMany()
                        .HasForeignKey("ProductChangeFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyPDV.BackEnd.Domain.Entities.Product", "ProductChangeTo")
                        .WithMany()
                        .HasForeignKey("ProductChangeToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductChangeFrom");

                    b.Navigation("ProductChangeTo");
                });

            modelBuilder.Entity("EasyPDV.BackEnd.Domain.Entities.RegularSale", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
